### ISSUE TITLE
Improvement: add desired_r_cutoff argument

### ISSUE THREAD

**Issue by julien-roux** [BgeeDB/bgee_pipeline#10]
https://github.com/BgeeDB/bgee_pipeline/blob/1cddf15123bcd3e7a318300f218c1a3ca8ce941c/pipeline/RNA_Seq/1Run/rna_seq_presence_absence.R#L142

It would be nice to add an argument to this function (for example called `desired_r_cutoff`) that replaces the hard coded theshold of 0.05 throughout the script. The 0.05 value can be kept for now, but it is cleaner to define it only at once point in the script.

**Comment by SFonsecaCosta** [comment]
done (develop branch)
