### ISSUE TITLE
bug intergenic sequence size

### ISSUE THREAD

**Issue by jwollbrett** [BgeeDB/bgee_pipeline#14]
In the prepare_GTF.R script scientific notation is used when start or stop position of an intergenic region ended with a lot of 0.
The only case in bgee 14 is for intergenic region of Danio rerio called  23_2.9e+07_29017272 (chr 23, start position 29000000, stop position 29017272).
This scientific notation is wrongly interpreted to retrieve the intergenic sequence from fasta file, resulting in a sequence of 29017271 bp.

**Comment by jwollbrett** [comment]
This bug has been solved by changing the value of R option "scipen" from 0 to 999.
`options(scipen = 999)`
It disables scientific notation
https://stackoverflow.com/questions/5352099/how-to-disable-scientific-notation

**Comment by fbastian** [comment]
I suggest (as we try to do each time we find a bug) to add a control at the end of the pipeline step to verify that no Bgee intergenic regions are longer/shorter than expected.
