### ISSUE TITLE
Detect 3' or 5' mRNA sequencing

### ISSUE THREAD

**Issue by marcrr** [BgeeDB/bgee_pipeline#2]
Some RNA-seq protocols only sequence tags at 3' (or 5'?) end of transcript. They should be detected to be treated differently, e.g. no length correction to compute expression levels.

**Comment by SFonsecaCosta** [comment]
As a suggestion @smoretti we can highlight this protocols by searching for particular key words in the annotation files or in the informative file after download. Protocols like: MACE-Seq, QuantSeq 3', RACE 3' and 5' should be filtered.

**Comment by smoretti** [comment]
Added

**Comment by SFonsecaCosta** [comment]
This libraries strategies are not included for the moment in our RNA-Seq pipeline (so far this is not an issue).
I will close the issue since this is more future work.
