### ISSUE TITLE
Increase kallisto index for short reads

### ISSUE THREAD

**Issue by smoretti** [BgeeDB/bgee_pipeline#8]
Increase kallisto index for short reads:

Move from 15 to 21 nt k-mer length. This is what people look to do.
See https://www.biostars.org/p/104321/
See https://groups.google.com/forum/#!topic/kallisto-sleuth-users/clOeSROnnFI

**Comment by smoretti** [comment]
People look to use 21-mers for short reads according to posts. But this is something to discuss

**Comment by SFonsecaCosta** [comment]
@smoretti @julien-roux exist same paper that highlight that, use of Kmer 21:
https://jyunyu.csie.org/docs/pubs/acmbcb2017paper.pdf
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6042521/
Also in this discussion Ppmelsted recommend K21 (for 26bp long)
https://github.com/pachterlab/kallisto/issues/76#issuecomment-134620678
But if everybody agree we can keep k15.

**Comment by julien-roux** [comment]
If there is documentation ot back up the use of 21bp, it makes sense to change then. Could it be problematic for miRNA-seq though?

**Comment by SFonsecaCosta** [comment]
I will look if this can be problematic for miRNA, but the average in length is around 21-25 nucleotides.

**Comment by SFonsecaCosta** [comment]
For Bgee15 we agree to keep k-mers of 15, for short reads. Since we will also include miRNA libraries.
