### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by julien-roux** [BgeeDB/bgee_pipeline#9]
https://github.com/BgeeDB/bgee_pipeline/blob/1cddf15123bcd3e7a318300f218c1a3ca8ce941c/pipeline/RNA_Seq/1Run/rna_seq_presence_absence.R#L259

With Sara we found a small bug affecting the presence/absence script. This should have very minor effect but still needs to be fixed. We should use `<=` instead of `<` in the line 259:

`sum_by_species$tpm <= max_intergenic`

**Comment by SFonsecaCosta** [comment]
bug fixed (develop branch)
